// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.commands;

import java.io.IOException;
import java.util.List;
import io.quantumdb.cli.utils.CliException;
import io.quantumdb.cli.utils.CliWriter;
import io.quantumdb.cli.utils.CliWriter.Context;
import io.quantumdb.core.backends.Backend;
import io.quantumdb.core.backends.Config;
import io.quantumdb.core.versioning.RefLog;
import io.quantumdb.core.versioning.State;

public class Status extends Command {
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(Status.class);

    @Override
    public Identifier getIdentifier() {
        return new Identifier("status", "Display currently available versions of the database schema.");
    }

    @Override
    public void perform(CliWriter writer, List<String> arguments) {
        try {
            Config config = Config.load();
            Backend backend = config.getBackend();
            State state = loadState(backend);
            RefLog refLog = state.getRefLog();
            writeDatabaseState(writer, refLog, state.getChangelog());
        } catch (IOException | CliException e) {
            log.error(e.getMessage(), e);
            writer.write(e.getMessage(), Context.FAILURE);
        }
    }
}
