// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.xml;

import static com.google.common.base.Preconditions.checkArgument;
import java.util.List;
import java.util.stream.Collectors;
import com.google.common.collect.Lists;

public class XmlChangeset {
    static XmlChangeset convert(XmlElement element) {
        checkArgument(element.getTag().equals("changeset"));
        XmlChangeset changeset = new XmlChangeset();
        changeset.setId(element.getAttributes().get("id"));
        changeset.setAuthor(element.getAttributes().get("author"));
        for (XmlElement child : element.getChildren()) {
            if (child.getTag().equals("operations")) {
                for (XmlElement subChild : child.getChildren()) {
                    changeset.getOperations().add(XmlOperation.convert(subChild));
                }
            } else if (child.getTag().equals("description")) {
                String description = child.getChildren()
                                          .stream()
                                          .filter(subChild -> subChild.getTag() == null)
                                          .filter(subChild -> subChild.getText() != null)
                                          .map(XmlElement::getText)
                                          .collect(Collectors.joining());
                changeset.setDescription(description);
            }
        }
        return changeset;
    }

    private String                      author;
    private String                      description;
    private String                      id;
    private final List<XmlOperation<?>> operations = Lists.newArrayList();

    @java.lang.SuppressWarnings("all")
    public XmlChangeset() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof XmlChangeset))
            return false;
        final XmlChangeset other = (XmlChangeset) o;
        if (!other.canEqual(this))
            return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id))
            return false;
        final java.lang.Object this$author = this.getAuthor();
        final java.lang.Object other$author = other.getAuthor();
        if (this$author == null ? other$author != null : !this$author.equals(other$author))
            return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description))
            return false;
        final java.lang.Object this$operations = this.getOperations();
        final java.lang.Object other$operations = other.getOperations();
        if (this$operations == null ? other$operations != null : !this$operations.equals(other$operations))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    public String getAuthor() {
        return this.author;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public List<XmlOperation<?>> getOperations() {
        return this.operations;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $author = this.getAuthor();
        result = result * PRIME + ($author == null ? 43 : $author.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $operations = this.getOperations();
        result = result * PRIME + ($operations == null ? 43 : $operations.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public void setAuthor(final String author) {
        this.author = author;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "XmlChangeset(id=" + this.getId() + ", author=" + this.getAuthor() + ", description="
                + this.getDescription() + ", operations=" + this.getOperations() + ")";
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof XmlChangeset;
    }
}
