// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.xml;

import static com.google.common.base.Preconditions.checkArgument;
import io.quantumdb.core.schema.operations.DropView;
import io.quantumdb.core.schema.operations.SchemaOperations;

public class XmlDropView implements XmlOperation<DropView> {
    static final String TAG = "dropView";

    static XmlOperation<?> convert(XmlElement element) {
        checkArgument(element.getTag().equals(TAG));
        XmlDropView operation = new XmlDropView();
        operation.setViewName(element.getAttributes().get("viewName"));
        return operation;
    }

    private String viewName;

    
    public XmlDropView() {
    }

    @java.lang.Override
    
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof XmlDropView))
            return false;
        final XmlDropView other = (XmlDropView) o;
        if (!other.canEqual(this))
            return false;
        final java.lang.Object this$viewName = this.getViewName();
        final java.lang.Object other$viewName = other.getViewName();
        if (this$viewName == null ? other$viewName != null : !this$viewName.equals(other$viewName))
            return false;
        return true;
    }

    
    public String getViewName() {
        return this.viewName;
    }

    @java.lang.Override
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $viewName = this.getViewName();
        result = result * PRIME + ($viewName == null ? 43 : $viewName.hashCode());
        return result;
    }

    
    public void setViewName(final String viewName) {
        this.viewName = viewName;
    }

    @Override
    public DropView toOperation() {
        return SchemaOperations.dropView(viewName);
    }

    @java.lang.Override
    
    public java.lang.String toString() {
        return "XmlDropView(viewName=" + this.getViewName() + ")";
    }

    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof XmlDropView;
    }
}
