// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.xml;

import static com.google.common.base.Preconditions.checkArgument;
import io.quantumdb.core.schema.operations.DropTable;
import io.quantumdb.core.schema.operations.SchemaOperations;

public class XmlDropTable implements XmlOperation<DropTable> {
    static final String TAG = "dropTable";

    static XmlOperation<?> convert(XmlElement element) {
        checkArgument(element.getTag().equals(TAG));
        XmlDropTable operation = new XmlDropTable();
        operation.setTableName(element.getAttributes().get("tableName"));
        return operation;
    }

    private String tableName;

    
    public XmlDropTable() {
    }

    @java.lang.Override
    
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof XmlDropTable))
            return false;
        final XmlDropTable other = (XmlDropTable) o;
        if (!other.canEqual(this))
            return false;
        final java.lang.Object this$tableName = this.getTableName();
        final java.lang.Object other$tableName = other.getTableName();
        if (this$tableName == null ? other$tableName != null : !this$tableName.equals(other$tableName))
            return false;
        return true;
    }

    
    public String getTableName() {
        return this.tableName;
    }

    @java.lang.Override
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $tableName = this.getTableName();
        result = result * PRIME + ($tableName == null ? 43 : $tableName.hashCode());
        return result;
    }

    
    public void setTableName(final String tableName) {
        this.tableName = tableName;
    }

    @Override
    public DropTable toOperation() {
        return SchemaOperations.dropTable(tableName);
    }

    @java.lang.Override
    
    public java.lang.String toString() {
        return "XmlDropTable(tableName=" + this.getTableName() + ")";
    }

    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof XmlDropTable;
    }
}
