// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.xml;

import static com.google.common.base.Preconditions.checkArgument;
import io.quantumdb.core.schema.operations.DropIndex;
import io.quantumdb.core.schema.operations.SchemaOperations;

public class XmlDropIndex implements XmlOperation<DropIndex> {
    static final String TAG = "dropIndex";

    static XmlOperation<?> convert(XmlElement element) {
        checkArgument(element.getTag().equals(TAG));
        XmlDropIndex operation = new XmlDropIndex();
        operation.setTableName(element.getAttributes().get("tableName"));
        operation.setColumnNames(element.getAttributes().get("columnNames").split(","));
        return operation;
    }

    private String[] columnNames;
    private String   tableName;

    
    public XmlDropIndex() {
    }

    @java.lang.Override
    
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof XmlDropIndex))
            return false;
        final XmlDropIndex other = (XmlDropIndex) o;
        if (!other.canEqual(this))
            return false;
        final java.lang.Object this$tableName = this.getTableName();
        final java.lang.Object other$tableName = other.getTableName();
        if (this$tableName == null ? other$tableName != null : !this$tableName.equals(other$tableName))
            return false;
        if (!java.util.Arrays.deepEquals(this.getColumnNames(), other.getColumnNames()))
            return false;
        return true;
    }

    
    public String[] getColumnNames() {
        return this.columnNames;
    }

    
    public String getTableName() {
        return this.tableName;
    }

    @java.lang.Override
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $tableName = this.getTableName();
        result = result * PRIME + ($tableName == null ? 43 : $tableName.hashCode());
        result = result * PRIME + java.util.Arrays.deepHashCode(this.getColumnNames());
        return result;
    }

    
    public void setColumnNames(final String[] columnNames) {
        this.columnNames = columnNames;
    }

    
    public void setTableName(final String tableName) {
        this.tableName = tableName;
    }

    @Override
    public DropIndex toOperation() {
        return SchemaOperations.dropIndex(tableName, columnNames);
    }

    @java.lang.Override
    
    public java.lang.String toString() {
        return "XmlDropIndex(tableName=" + this.getTableName() + ", columnNames="
                + java.util.Arrays.deepToString(this.getColumnNames()) + ")";
    }

    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof XmlDropIndex;
    }
}
