// Generated by delombok at Thu Mar 11 18:53:10 PST 2021
package io.quantumdb.cli.xml;

import static com.google.common.base.Preconditions.checkArgument;
import io.quantumdb.core.schema.operations.RenameTable;
import io.quantumdb.core.schema.operations.SchemaOperations;

public class XmlRenameTable implements XmlOperation<RenameTable> {
	static final String TAG = "renameTable";

	static XmlOperation convert(XmlElement element) {
		checkArgument(element.getTag().equals(TAG));
		XmlRenameTable operation = new XmlRenameTable();
		operation.setOldTableName(element.getAttributes().get("oldTableName"));
		operation.setNewTableName(element.getAttributes().get("newTableName"));
		return operation;
	}

	private String oldTableName;
	private String newTableName;

	@Override
	public RenameTable toOperation() {
		return SchemaOperations.renameTable(oldTableName, newTableName);
	}

	@java.lang.SuppressWarnings("all")
	public XmlRenameTable() {
	}

	@java.lang.SuppressWarnings("all")
	public String getOldTableName() {
		return this.oldTableName;
	}

	@java.lang.SuppressWarnings("all")
	public String getNewTableName() {
		return this.newTableName;
	}

	@java.lang.SuppressWarnings("all")
	public void setOldTableName(final String oldTableName) {
		this.oldTableName = oldTableName;
	}

	@java.lang.SuppressWarnings("all")
	public void setNewTableName(final String newTableName) {
		this.newTableName = newTableName;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof XmlRenameTable)) return false;
		final XmlRenameTable other = (XmlRenameTable) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$oldTableName = this.getOldTableName();
		final java.lang.Object other$oldTableName = other.getOldTableName();
		if (this$oldTableName == null ? other$oldTableName != null : !this$oldTableName.equals(other$oldTableName)) return false;
		final java.lang.Object this$newTableName = this.getNewTableName();
		final java.lang.Object other$newTableName = other.getNewTableName();
		if (this$newTableName == null ? other$newTableName != null : !this$newTableName.equals(other$newTableName)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof XmlRenameTable;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $oldTableName = this.getOldTableName();
		result = result * PRIME + ($oldTableName == null ? 43 : $oldTableName.hashCode());
		final java.lang.Object $newTableName = this.getNewTableName();
		result = result * PRIME + ($newTableName == null ? 43 : $newTableName.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "XmlRenameTable(oldTableName=" + this.getOldTableName() + ", newTableName=" + this.getNewTableName() + ")";
	}
}
