// Generated by delombok at Thu Mar 11 18:53:07 PST 2021
package io.quantumdb.core.schema.definitions;

public class Sequence {
	private String name;
	private Catalog parent;

	public Sequence(String name) {
		this.name = name;
	}

	void setParent(Catalog parent) {
		this.parent = parent;
	}

	public Sequence rename(String newName) {
		this.name = newName;
		return this;
	}

	public String toString() {
		return PrettyPrinter.prettyPrint(this);
	}

	public Sequence copy() {
		return new Sequence(name);
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public Catalog getParent() {
		return this.parent;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Sequence)) return false;
		final Sequence other = (Sequence) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Sequence;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		return result;
	}
}
