/*
 * This file is generated by jOOQ.
 */
package com.apollo.qdb.quantumdbSchema.tables.records;


import com.apollo.qdb.quantumdbSchema.tables.Refs;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefsRecord extends UpdatableRecordImpl<RefsRecord> implements Record1<String> {

    private static final long serialVersionUID = -1690925676;

    /**
     * Setter for <code>QUANTUMDB.REFS.REF_ID</code>.
     */
    public void setRefId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>QUANTUMDB.REFS.REF_ID</code>.
     */
    public String getRefId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Refs.REFS.REF_ID;
    }

    @Override
    public String component1() {
        return getRefId();
    }

    @Override
    public String value1() {
        return getRefId();
    }

    @Override
    public RefsRecord value1(String value) {
        setRefId(value);
        return this;
    }

    @Override
    public RefsRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefsRecord
     */
    public RefsRecord() {
        super(Refs.REFS);
    }

    /**
     * Create a detached, initialised RefsRecord
     */
    public RefsRecord(String refId) {
        super(Refs.REFS);

        set(0, refId);
    }
}
