// Generated by delombok at Thu Mar 11 18:53:07 PST 2021
package io.quantumdb.core.migration.operations;

import io.quantumdb.core.schema.definitions.Catalog;
import io.quantumdb.core.schema.definitions.View;
import io.quantumdb.core.schema.operations.CreateView;
import io.quantumdb.core.utils.RandomHasher;
import io.quantumdb.core.versioning.RefLog;
import io.quantumdb.core.versioning.Version;

class CreateViewMigrator implements SchemaOperationMigrator<CreateView> {
	@Override
	public void migrate(Catalog catalog, RefLog refLog, Version version, CreateView operation) {
		String refId = RandomHasher.generateRefId(refLog);
		String viewName = operation.getViewName();
		refLog.fork(version);
		refLog.addView(viewName, refId, version);
		View view = new View(refId, operation.getQuery());
		catalog.addView(view);
	}

	@java.lang.SuppressWarnings("all")
	CreateViewMigrator() {
	}
}
