/*
 * This file is generated by jOOQ.
 */
package com.apollo.qdb.quantumdbSchema;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in QUANTUMDB
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>QUANTUMDB.COLUMN_MAPPINGS_ID</code>
     */
    public static final Sequence<Long> COLUMN_MAPPINGS_ID = Internal.createSequence("COLUMN_MAPPINGS_ID", Quantumdb.QUANTUMDB, org.jooq.impl.SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>QUANTUMDB.SYNCHRONIZER_COLUMNS_ID</code>
     */
    public static final Sequence<Long> SYNCHRONIZER_COLUMNS_ID = Internal.createSequence("SYNCHRONIZER_COLUMNS_ID", Quantumdb.QUANTUMDB, org.jooq.impl.SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>QUANTUMDB.SYNCHRONIZERS_ID</code>
     */
    public static final Sequence<Long> SYNCHRONIZERS_ID = Internal.createSequence("SYNCHRONIZERS_ID", Quantumdb.QUANTUMDB, org.jooq.impl.SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>QUANTUMDB.TABLE_COLUMNS_ID</code>
     */
    public static final Sequence<Long> TABLE_COLUMNS_ID = Internal.createSequence("TABLE_COLUMNS_ID", Quantumdb.QUANTUMDB, org.jooq.impl.SQLDataType.BIGINT, null, null, null, null, false, null);
}
