/*
 * This file is generated by jOOQ.
 */
package com.apollo.qdb.quantumdbSchema;


import com.apollo.qdb.quantumdbSchema.tables.ActiveVersions;
import com.apollo.qdb.quantumdbSchema.tables.Changelog;
import com.apollo.qdb.quantumdbSchema.tables.Changesets;
import com.apollo.qdb.quantumdbSchema.tables.ColumnMappings;
import com.apollo.qdb.quantumdbSchema.tables.Config;
import com.apollo.qdb.quantumdbSchema.tables.RefVersions;
import com.apollo.qdb.quantumdbSchema.tables.Refs;
import com.apollo.qdb.quantumdbSchema.tables.SynchronizerColumns;
import com.apollo.qdb.quantumdbSchema.tables.Synchronizers;
import com.apollo.qdb.quantumdbSchema.tables.TableColumns;


/**
 * Convenience access to all tables in QUANTUMDB
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>QUANTUMDB.ACTIVE_VERSIONS</code>.
     */
    public static final ActiveVersions ACTIVE_VERSIONS = ActiveVersions.ACTIVE_VERSIONS;

    /**
     * The table <code>QUANTUMDB.CHANGELOG</code>.
     */
    public static final Changelog CHANGELOG = Changelog.CHANGELOG;

    /**
     * The table <code>QUANTUMDB.CHANGESETS</code>.
     */
    public static final Changesets CHANGESETS = Changesets.CHANGESETS;

    /**
     * The table <code>QUANTUMDB.COLUMN_MAPPINGS</code>.
     */
    public static final ColumnMappings COLUMN_MAPPINGS = ColumnMappings.COLUMN_MAPPINGS;

    /**
     * The table <code>QUANTUMDB.CONFIG</code>.
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * The table <code>QUANTUMDB.REF_VERSIONS</code>.
     */
    public static final RefVersions REF_VERSIONS = RefVersions.REF_VERSIONS;

    /**
     * The table <code>QUANTUMDB.REFS</code>.
     */
    public static final Refs REFS = Refs.REFS;

    /**
     * The table <code>QUANTUMDB.SYNCHRONIZER_COLUMNS</code>.
     */
    public static final SynchronizerColumns SYNCHRONIZER_COLUMNS = SynchronizerColumns.SYNCHRONIZER_COLUMNS;

    /**
     * The table <code>QUANTUMDB.SYNCHRONIZERS</code>.
     */
    public static final Synchronizers SYNCHRONIZERS = Synchronizers.SYNCHRONIZERS;

    /**
     * The table <code>QUANTUMDB.TABLE_COLUMNS</code>.
     */
    public static final TableColumns TABLE_COLUMNS = TableColumns.TABLE_COLUMNS;
}
